apiVersion: v1
kind: Service
metadata:
  name: plex-webhook
  namespace: media
spec:
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: plex-webhook
  sessionAffinity: None
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: hypomos-webhook-lb
  namespace: media
spec:
  selector:
    app: hypomos-webhook
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-webhook
  namespace: media
  labels:
    app: plex-webhook
spec:
  selector:
    matchLabels:
      app: plex-webhook
  template:
    metadata:
      labels:
        app: plex-webhook
    spec:
      containers:
      - name: plex-webhook
        image: ${CICD_REGISTRY}/plex-webhook:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
